spring:
  application:
    name: ec2-payment-system

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-millis: ${JWT_ACCESS_TOKEN_EXPIRATION_MILLIS}
portone:
  base-url: ${PORTONE_BASE_URL:https://api.portone.io}
  api-secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}
  webhook-secret: ${PORTONE_WEBHOOK_SECRET}
